### ISSUE TITLE
Error deleting default DHCP options

### ISSUE THREAD

**Issue by jplock** [aws-samples/aws-control-tower-account-setup-using-step-functions#9]
```
[ERROR] ClientError: An error occurred (InvalidDhcpOptionsId.Malformed) when calling the DeleteDhcpOptions operation: The dhcp-options ID 'default' is malformed
Traceback (most recent call last):
  File "/opt/python/aws_lambda_powertools/middleware_factory/factory.py", line 134, in wrapper
    response = middleware()
  File "/opt/python/aws_lambda_powertools/utilities/validation/validator.py", line 129, in validator
    response = handler(event, context)
  File "/opt/python/aws_lambda_powertools/tracing/tracer.py", line 305, in decorate
    response = lambda_handler(event, context, **kwargs)
  File "/opt/python/aws_lambda_powertools/logging/logger.py", line 442, in decorate
    return lambda_handler(event, context, *args, **kwargs)
  File "/var/task/account_setup/lambda_handler.py", line 54, in handler
    ec2.delete_vpc(default_vpc_id)
  File "/var/task/account_setup/resources/ec2.py", line 85, in delete_vpc
    vpc.dhcp_options.delete()
  File "/opt/python/boto3/resources/factory.py", line 580, in do_action
    response = action(self, *args, **kwargs)
  File "/opt/python/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/opt/python/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/python/aws_xray_sdk/ext/botocore/patch.py", line 38, in _xray_traced_botocore
    return xray_recorder.record_subsegment(
  File "/opt/python/aws_xray_sdk/core/recorder.py", line 462, in record_subsegment
    six.raise_from(exc, exc)
  File "<string>", line 3, in raise_from
  File "/opt/python/aws_xray_sdk/core/recorder.py", line 457, in record_subsegment
    return_value = wrapped(*args, **kwargs)
  File "/opt/python/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
```

in regions: sa-east-1, ca-central-1

**Comment by jplock** [comment]
Fixed in ae724922fce7b09f8300e8cf14276cf20663fa32
